### ISSUE TITLE
My window can't run this.

### ISSUE THREAD

**Issue by phamhuutruong7** [agebhar1/sim8008#1]
I download this from the site of IMN in HTWK but after i extract it, the anti-virus said this file is dangerous. 
Even if i turn the anti-virus off and then run it. It said the the window can't run it.
Do you have any idea to solve my problem?

**Comment by agebhar1** [comment]
Hi @phamhuutruong7 which version of Windows do you use? If possible share a screenshot, only the part with the dialog.

**Comment by phamhuutruong7** [comment]
![capture3](https://user-images.githubusercontent.com/19285094/37921755-f3df2044-312a-11e8-9152-88747657600f.PNG)
![capture4](https://user-images.githubusercontent.com/19285094/37921832-29d3c20e-312b-11e8-8c1d-1a732fd0781f.PNG)

thank you for your quick reply.

**Comment by agebhar1** [comment]
It seems Windows also (falsy) detect malicious code in the binary https://www.drivereasy.com/knowledge/this-app-cant-run-on-your-pc-solved/ Maybe you try one of the solutions. Alternatively you can run the binary on Linux with Wine.

**Comment by phamhuutruong7** [comment]
ok thanks for your advice.
on you link above that has 4 Options, none of them works. 
but it works with the other option. It just need to perform a clean boot.
So in case someone else ask you the same question, here is my solution for that. thanks alot

**Comment by agebhar1** [comment]
You're welcome. I close this issue since it's solved.
